export const COURSE_FULL_NAMES: Record<string, string> = {
  // South Africa — KwaZulu-Natal
  GF: 'Greyville (Flat)',
  GT: 'Greyville (Turf)',
  GV: 'Greyville Racecourse',
  Greyville: 'Greyville Racecourse, Durban',
  Scottsville: 'Scottsville Racecourse, Pietermaritzburg',
  // South Africa — Gauteng
  TPF: 'Turffontein Racecourse',
  Turffontein: 'Turffontein Racecourse, Johannesburg',
  Vaal: 'Vaal Racecourse, Johannesburg',
  Emerald: 'Emerald Casino & Resort, Vanderbijlpark',
  Sportsground: 'Germiston Sportsground',
  // South Africa — Western Cape
  Kenilworth: 'Kenilworth Racecourse, Cape Town',
  Durbanville: 'Durbanville Racecourse, Cape Town',
  // South Africa — Eastern Cape
  Fairview: 'Fairview Racecourse, Port Elizabeth',
  PE: 'Fairview Racecourse, Port Elizabeth',
  // South Africa — Northern Cape
  FP: 'Flamingo Park, Kimberley',
  'Flamingo Park': 'Flamingo Park, Kimberley',
  // Zimbabwe
  Borrowdale: 'Borrowdale Park, Harare',
  'Borrowdale Park': 'Borrowdale Park, Harare',
  // United Kingdom
  Ascot: 'Ascot Racecourse, Berkshire',
  Asc: 'Ascot Racecourse, Berkshire',
  Cheltenham: 'Cheltenham Racecourse, Gloucestershire',
  Chl: 'Cheltenham Racecourse, Gloucestershire',
  Sandown: 'Sandown Park, Surrey',
  Sdw: 'Sandown Park, Surrey',
  Newmarket: 'Newmarket Racecourse, Suffolk',
  Nmk: 'Newmarket Racecourse, Suffolk',
  Epsom: 'Epsom Downs Racecourse, Surrey',
  Eps: 'Epsom Downs Racecourse, Surrey',
  Goodwood: 'Goodwood Racecourse, West Sussex',
  Gwd: 'Goodwood Racecourse, West Sussex',
  York: 'York Racecourse, North Yorkshire',
  Yrk: 'York Racecourse, North Yorkshire',
  Chester: 'Chester Racecourse, Cheshire',
  Ctr: 'Chester Racecourse, Cheshire',
  Doncaster: 'Doncaster Racecourse, South Yorkshire',
  Don: 'Doncaster Racecourse, South Yorkshire',
  Leicester: 'Leicester Racecourse, Leicestershire',
  Lei: 'Leicester Racecourse, Leicestershire',
  Nottingham: 'Nottingham Racecourse, Nottinghamshire',
  Not: 'Nottingham Racecourse, Nottinghamshire',
  Windsor: 'Windsor Racecourse, Berkshire',
  Wdr: 'Windsor Racecourse, Berkshire',
  Haydock: 'Haydock Park, Merseyside',
  Hay: 'Haydock Park, Merseyside',
  Aintree: 'Aintree Racecourse, Liverpool',
  Ain: 'Aintree Racecourse, Liverpool',
  Wincanton: 'Wincanton Racecourse, Somerset',
  Wnc: 'Wincanton Racecourse, Somerset',
  Wetherby: 'Wetherby Racecourse, West Yorkshire',
  Wth: 'Wetherby Racecourse, West Yorkshire',
  Perth: 'Perth Racecourse, Perthshire',
  Prc: 'Perth Racecourse, Perthshire',
  Sedgefield: 'Sedgefield Racecourse, Durham',
  Sdg: 'Sedgefield Racecourse, Durham',
  Cartmel: 'Cartmel Racecourse, Cumbria',
  Car: 'Cartmel Racecourse, Cumbria',
  Catterick: 'Catterick Bridge, North Yorkshire',
  Crt: 'Catterick Bridge, North Yorkshire',
  Folkestone: 'Folkestone Racecourse, Kent',
  Flk: 'Folkestone Racecourse, Kent',
  Fontwell: 'Fontwell Park, West Sussex',
  Fnt: 'Fontwell Park, West Sussex',
  Hereford: 'Hereford Racecourse, Herefordshire',
  Her: 'Hereford Racecourse, Herefordshire',
  Hexham: 'Hexham Racecourse, Northumberland',
  Hex: 'Hexham Racecourse, Northumberland',
  Huntingdon: 'Huntingdon Racecourse, Cambridgeshire',
  Hun: 'Huntingdon Racecourse, Cambridgeshire',
  Kelso: 'Kelso Racecourse, Scottish Borders',
  Kel: 'Kelso Racecourse, Scottish Borders',
  Kempton: 'Kempton Park, Surrey',
  Kmp: 'Kempton Park, Surrey',
  Lingfield: 'Lingfield Park, Surrey',
  Lng: 'Lingfield Park, Surrey',
  Ludlow: 'Ludlow Racecourse, Shropshire',
  Lud: 'Ludlow Racecourse, Shropshire',
  'Market Rasen': 'Market Rasen Racecourse, Lincolnshire',
  Mkt: 'Market Rasen Racecourse, Lincolnshire',
  Musselburgh: 'Musselburgh Racecourse, East Lothian',
  Mus: 'Musselburgh Racecourse, East Lothian',
  Newcastle: 'Newcastle Racecourse, Tyne & Wear',
  Ncl: 'Newcastle Racecourse, Tyne & Wear',
  'Newton Abbot': 'Newton Abbot Racecourse, Devon',
  Nwt: 'Newton Abbot Racecourse, Devon',
  Plumpton: 'Plumpton Racecourse, East Sussex',
  Plu: 'Plumpton Racecourse, East Sussex',
  Pontefract: 'Pontefract Racecourse, West Yorkshire',
  Pon: 'Pontefract Racecourse, West Yorkshire',
  Redcar: 'Redcar Racecourse, North Yorkshire',
  Rdc: 'Redcar Racecourse, North Yorkshire',
  Ripon: 'Ripon Racecourse, North Yorkshire',
  Rip: 'Ripon Racecourse, North Yorkshire',
  Salisbury: 'Salisbury Racecourse, Wiltshire',
  Sal: 'Salisbury Racecourse, Wiltshire',
  Southwell: 'Southwell Racecourse, Nottinghamshire',
  Swl: 'Southwell Racecourse, Nottinghamshire',
  Stratford: 'Stratford-on-Avon Racecourse, Warwickshire',
  Str: 'Stratford-on-Avon Racecourse, Warwickshire',
  Taunton: 'Taunton Racecourse, Somerset',
  Tau: 'Taunton Racecourse, Somerset',
  Thirsk: 'Thirsk Racecourse, North Yorkshire',
  Thi: 'Thirsk Racecourse, North Yorkshire',
  Towcester: 'Towcester Racecourse, Northamptonshire',
  Tow: 'Towcester Racecourse, Northamptonshire',
  Uttoxeter: 'Uttoxeter Racecourse, Staffordshire',
  Utt: 'Uttoxeter Racecourse, Staffordshire',
  Warwick: 'Warwick Racecourse, Warwickshire',
  Wwc: 'Warwick Racecourse, Warwickshire',
  Worcester: 'Worcester Racecourse, Worcestershire',
  Wor: 'Worcester Racecourse, Worcestershire',
  'Great Yarmouth': 'Great Yarmouth Racecourse, Norfolk',
  Yarmouth: 'Great Yarmouth Racecourse, Norfolk',
  Yar: 'Great Yarmouth Racecourse, Norfolk',
  // Ireland
  Leopardstown: 'Leopardstown Racecourse, Dublin',
  Lpd: 'Leopardstown Racecourse, Dublin',
  Curragh: 'The Curragh, County Kildare',
  Cur: 'The Curragh, County Kildare',
  Cork: 'Cork Racecourse, County Cork',
  Cor: 'Cork Racecourse, County Cork',
  Fairyhouse: 'Fairyhouse Racecourse, County Meath',
  Fhy: 'Fairyhouse Racecourse, County Meath',
  Galway: 'Galway Racecourse, County Galway',
  Gal: 'Galway Racecourse, County Galway',
  Gowran: 'Gowran Park, County Kilkenny',
  Gow: 'Gowran Park, County Kilkenny',
  Kilbeggan: 'Kilbeggan Racecourse, County Westmeath',
  Kbg: 'Kilbeggan Racecourse, County Westmeath',
  Killarney: 'Killarney Racecourse, County Kerry',
  Kil: 'Killarney Racecourse, County Kerry',
  Limerick: 'Limerick Racecourse, County Limerick',
  Lim: 'Limerick Racecourse, County Limerick',
  Listowel: 'Listowel Racecourse, County Kerry',
  Lis: 'Listowel Racecourse, County Kerry',
  Naas: 'Naas Racecourse, County Kildare',
  Naa: 'Naas Racecourse, County Kildare',
  Navan: 'Navan Racecourse, County Meath',
  Nav: 'Navan Racecourse, County Meath',
  Punchestown: 'Punchestown Racecourse, County Kildare',
  Pch: 'Punchestown Racecourse, County Kildare',
  Roscommon: 'Roscommon Racecourse, County Roscommon',
  Rsc: 'Roscommon Racecourse, County Roscommon',
  Sligo: 'Sligo Racecourse, County Sligo',
  Sli: 'Sligo Racecourse, County Sligo',
  Thurles: 'Thurles Racecourse, County Tipperary',
  Thu: 'Thurles Racecourse, County Tipperary',
  Tipperary: 'Tipperary Racecourse, County Tipperary',
  Tip: 'Tipperary Racecourse, County Tipperary',
  Tralee: 'Tralee Racecourse, County Kerry',
  Tra: 'Tralee Racecourse, County Kerry',
  // France
  Longchamp: 'ParisLongchamp Racecourse, Paris',
  Lch: 'ParisLongchamp Racecourse, Paris',
  Chantilly: 'Chantilly Racecourse, Oise',
  Cht: 'Chantilly Racecourse, Oise',
  Deauville: 'Deauville-La Touques, Calvados',
  Dev: 'Deauville-La Touques, Calvados',
  'Saint-Cloud': 'Saint-Cloud Racecourse, Hauts-de-Seine',
  Scl: 'Saint-Cloud Racecourse, Hauts-de-Seine',
  Auteuil: 'Auteuil Racecourse, Paris',
  Aut: 'Auteuil Racecourse, Paris',
  Enghien: 'Enghien-Soisy Racecourse, Val-d\'Oise',
  Eng: 'Enghien-Soisy Racecourse, Val-d\'Oise',
  // Australia
  Flemington: 'Flemington Racecourse, Melbourne',
  Flm: 'Flemington Racecourse, Melbourne',
  Randwick: 'Royal Randwick, Sydney',
  Rwk: 'Royal Randwick, Sydney',
  Caulfield: 'Caulfield Racecourse, Melbourne',
  Cfl: 'Caulfield Racecourse, Melbourne',
  Rosehill: 'Rosehill Gardens Racecourse, Sydney',
  Rsh: 'Rosehill Gardens Racecourse, Sydney',
  // USA
  'Churchill Downs': 'Churchill Downs, Louisville',
  Cdn: 'Churchill Downs, Louisville',
  Belmont: 'Belmont Park, New York',
  Bel: 'Belmont Park, New York',
  Saratoga: 'Saratoga Race Course, New York',
  Sar: 'Saratoga Race Course, New York',
  // Hong Kong
  'Sha Tin': 'Sha Tin Racecourse, Hong Kong',
  Sha: 'Sha Tin Racecourse, Hong Kong',
  'Happy Valley': 'Happy Valley Racecourse, Hong Kong',
  Hpv: 'Happy Valley Racecourse, Hong Kong',
  // Japan
  Tokyo: 'Tokyo Racecourse, Tokyo',
  Tok: 'Tokyo Racecourse, Tokyo',
  Kyoto: 'Kyoto Racecourse, Kyoto',
  Kyt: 'Kyoto Racecourse, Kyoto',
  Nakayama: 'Nakayama Racecourse, Chiba',
  Nak: 'Nakayama Racecourse, Chiba',
};

export function getFullCourseName(course: string): string {
  if (!course) return 'Unknown Venue';
  return COURSE_FULL_NAMES[course] ?? course;
}
